### ISSUE TITLE
Action attachment.store with conflict strategy 'update' caused an error

### ISSUE THREAD

**Issue by matt-jon35** [ahochsteger/gmail-processor#103]
Hello @ahochsteger,

I have been away for a few weeks and have come back and there have loads of changes, which is really exciting!  You helped me out with getting started and I have hit a little snag, but also need some guidance too if possible please.

I am using the 'ConflictStrategy: update' and even when running it in 'dangerous' mode, it still fails - works great until I try to use update.  Error as follows:

`2:28:16 PM	Info	[2023-09-01T13:28:16.799Z] DEBUG: Calling method 'store' ...
2:28:16 PM	Info	[2023-09-01T13:28:16.800Z] INFO: Storing attachment 'PORD-17659.pdf' to '/gtest2/PORD-17659.pdf' ...
2:28:17 PM	Info	[2023-09-01T13:28:17.478Z] WARN: A file with the same name already exists at location: /gtest2/PORD-17659.pdf. Updating the file contents.
2:28:17 PM	Info	[2023-09-01T13:28:17.479Z] INFO: Updating existing file 'PORD-17659.pdf' ...
2:28:17 PM	Info	[2023-09-01T13:28:17.480Z] ERROR: Action attachment.store caused an error: {}
2:28:17 PM	Info	[2023-09-01T13:28:17.481Z] INFO: Action result: {"ok":false,"error":{}}`

My config is as follows:

`  attachments: [
    {
      description: "Test run",
      match: {
        query: "-label:to-gdrive-processed -label:archive in:inbox from:redacted@redacted.co.uk subject:(Test2) has:attachment",
      },
      actions: [
        {
              name: "attachment.store",
              args: {
                location:
                  "/gtest2/${attachment.name}",
          conflictStrategy: 'update',
          },
        },
      ],
    },
  ],

  }`

Also, in the previous version I had different rules to process different emails like below, how do I replicate this now, I assume my understanding isn't quite right in terms of threads, messages and attachments, as I have only defined attachments in the above config.  I've tried using the convert tool, but it doesn't seem to convert into the correct format.

`{ // School A
"filter": "-label:to-gdrive-processed -label:archive in:inbox from:redacted@redacted.co.uk subject:(School A) has:attachment",
"folder": "'Home/School A'",
"archive": true
},

{ { // School B
"filter": "-label:to-gdrive-processed -label:archive in:inbox from:redacted@redacted.co.uk subject:(School B) has:attachment",
"folder": "'Home/School B'",
"archive": true
},`

Thank you so much for your help :)

**Comment by ahochsteger** [comment]
@matt-jon35 thanks for your kind words :)

I'll have to deeper investigate this issue which is a bit harder since the error message is missing in the log message. I guess I'll have to fix that first to get a step further.

Concerning your question about mutliple rules:
They roughly map to thread configs, but is now much better structured and allows a much more fine-grained matching than before.
If you have an old configuration from gmail2gdrive v1.x I recommend to convert that to the new format.
There's a section in the README that explains how to do that.

I hope that helps.

Andreas

**Comment by ahochsteger** [comment]
@matt-jon35 have you tried to use the conflict strategy 'replace' instead of 'update'?
Since 'update' tries to keep the file itself (including its ID and metadata) but just update its contents there may be edge cases where this does not work.
In this case 'replace' might still work, since it just removes the old file and creates a new one (resulting in a new file ID).
Let me know, if that worked.

**Comment by ahochsteger** [comment]
@matt-jon35 v2.0.5 fixes a bug concerning action error handling.
It would be great, if you could give it a try.
If it still fails, at least it should tell now why in the logs.

**Comment by ahochsteger** [comment]
Assuming the issue is closed now.
