### ISSUE TITLE
Use Subject line as new folder name

### ISSUE THREAD

**Issue by Dputz** [ahochsteger/gmail-processor#18]
Is there a method to save the attachment to a folder based on the subject line of the email? Dputz@jkpholdings.com

**Comment by Dputz** [comment]
Is this possible?

**Comment by ahochsteger** [comment]
Hi,

sorry for the late reply.

Currently the substitution logic is only implemented for the filename.
But it would not be that hard to extract that logic into its own function that can then be used for both the folder name and the filename.

If you want to give it a try I'd be happy to include the extension :-).

Regards,
Andreas

**Comment by Dputz** [comment]
That would be great.  Im trying to direct these to different folders.

**Comment by ahochsteger** [comment]
@Dputz, have a look at the proposal I've written in the [comment to issue #6](https://github.com/ahochsteger/gmail2gdrive/issues/6#issuecomment-487402411) and let me know if this would solve your use case.

**Comment by ahochsteger** [comment]
I'm closing this issue since [GMail2GDrive](https://github.com/ahochsteger/gmail-processor/tree/1.x) is discontinued and has been superseded by the much improved [Gmail Processor](https://github.com/ahochsteger/gmail-processor).
It provides very flexible ways to specify the storage location. 
See the [Getting Started Guide](https://github.com/ahochsteger/gmail-processor/tree/main#getting-started) as well as the [Reference Docs](https://github.com/ahochsteger/gmail-processor/blob/main/docs/reference-docs.md#substitution-placeholder) for more information
