### ISSUE TITLE
Overwrite Existing File

### ISSUE THREAD

**Issue by marcusjb** [ahochsteger/gmail-processor#19]
If the file already exists in the GDrive Path how can we have it overwrite instead of creating a duplicate filename?

**Comment by ahochsteger** [comment]
It should work using file.setContent().

See the following links for more details:
* https://developers.google.com/apps-script/reference/drive/file#setContent(String)
* https://stackoverflow.com/questions/14965442/how-to-delete-overwrite-csv-file-using-google-apps-script

**Comment by soetheman** [comment]
At line 94 I replaced:
     var file = folder.createFile(attachment);
with:
      var fileName = attachment.getName();
      var f = folder.getFilesByName(fileName);
      var file = f.hasNext() ? f.next() : folder.createFile(attachment);
However my Gmail2Gdrive script still is duplicating filenames on Gdrive instead of overwriting the existing files. 
Please advise.

**Comment by chaoscreater** [comment]
Sorry mate, I'm not a programmer, not sure why it's not working for you but it works for me. Have you tried saving your script?

Here's the question I posted on Stackoverflow, you might find it useful:

https://stackoverflow.com/questions/53221266/modify-google-app-script-gmail-to-google-drive/53221832?noredirect=1#comment93331540_53221832

**Comment by soetheman** [comment]
@chaoscreater 
Thank you for your feedback. 

Did some more testing (*) with the Gmail2Gdrive script and noticed that several file system related issues arise:
- Multiple files with the same name are present on Gdrive after time based TRIGGERING (**) of the Gmail2Gdrive script.
- Overwriting an existing file seems the take place properly after EXECUTING the function Gmail2Gdrive from the browser script menu, in case a new file is processed from the Gmail inbox. The newest file is written correctly on Gdrive:
- Deleting of an existing file takes place after running the function Gmail2Gdrive from the browser script menu (NO time based triggering) in case NO new file is present in email inbox. In this scenario however the oldest file is kept while the newest file(s) is/are being deleted ... (***):

Did you use time based triggering as well to run the script? For me this method is the only option to deploy it in an useful way.

*) I tested with both Gmail2Gdrive script modifications mentioned at https://stackoverflow.com/questions/53221266/modify-google-app-script-gmail-to-google-drive/53221832?noredirect=1#comment93331540_53221832

**) When you use simple triggers to run an Apps Script, it runs in a sandbox with reduced permissions. (Ref: Answer 1 @ https://stackoverflow.com/questions/26661545/createfile-in-google-apps-script-is-not-functioning-properly

***) I'm not a programmer either. But I would expect some more clever behavior from the code (or the file system?) just overwriting a duplicated file name :-)

Thanks,

**Comment by chaoscreater** [comment]
Hi mate,

From what I understand, the 3 lines of code translated to plain English is this:

- Check whether the filename exists in the folder. If exist, skip, otherwise create the file. 

So based on that, I don't think it creates the file and then deletes the file. I think it simply creates only when the filename is unique.

And yes, I do have a time based trigger for my Google Script. Kind of pointless if you were to run it manually?

**Comment by ahochsteger** [comment]
I'm closing this issue since [GMail2GDrive](https://github.com/ahochsteger/gmail-processor/tree/1.x) is discontinued and has been superseded by the much improved [Gmail Processor](https://github.com/ahochsteger/gmail-processor).
It allows to specify conflict resolution strategies among which 'overwrite' is the one you were looking for. 
See the [Getting Started Guide](https://github.com/ahochsteger/gmail-processor/tree/main#getting-started) as well as the [Reference Docs](https://github.com/ahochsteger/gmail-processor/blob/main/docs/reference-docs.md#substitution-placeholder) for more information
