### ISSUE TITLE
One email gets handled as a multiple

### ISSUE THREAD

**Issue by DanielZanchi** [ahochsteger/gmail-processor#324]
I'm trying to save the attachment of every email to google drive. 
The process works more or less but it is getting other messages connected, i don't know how, to that email:
<img width="1174" alt="image" src="https://github.com/ahochsteger/gmail-processor/assets/6886116/93b7dae9-a280-4b0f-af07-eaa7507dce98">
with this config:
`{
  "description": "This is a simple configuration example.",
  "settings": {
    "markProcessedMethod": "add-label",
    "markProcessedLabel": "to-gdrive/processed",
    "maxRuntime": 320,
    "sleepTimeThreads": 100,
    "sleepTimeMessages": 0,
    "sleepTimeAttachments": 0
  },
  "global": {},
  "messages": [
    {
      "description": "Store attachment from a message",
      "match": {
        "query": "has:attachment -in:trash -in:drafts -in:spam -label:to-gdrive/processed -in:sent newer_than:2m",
      },
      "attachments": [
        {
          "actions": [
            {
              "name": "attachment.store",
              "args": {
                "location": "GmailProcessor-Tests/Apple - ${message.date} - ${attachment.name}.pdf",
                "conflictStrategy": "skip"
              }
            }
          ]
        }
      ]
    }
  ]
}`

produces this result:
<img width="465" alt="image" src="https://github.com/ahochsteger/gmail-processor/assets/6886116/2246659a-e7d4-4ace-91d0-9f4227c7d113">
It's getting also other emails that were already processed and had the label the script is adding "to-gdrive/processed".

this is process summary:
```
6:09:38 PM	Info	[2024-03-27T17:09:38.072Z] INFO: Processing summary:
6:09:38 PM	Info	[2024-03-27T17:09:38.074Z] INFO:  - Processed thread configs: 1
6:09:38 PM	Info	[2024-03-27T17:09:38.079Z] INFO:  - Processed threads: 1
6:09:38 PM	Info	[2024-03-27T17:09:38.084Z] INFO:  - Processed message configs: 1
6:09:38 PM	Info	[2024-03-27T17:09:38.088Z] INFO:  - Processed messages: 6
6:09:38 PM	Info	[2024-03-27T17:09:38.090Z] INFO:  - Processed attachment configs: 6
6:09:38 PM	Info	[2024-03-27T17:09:38.091Z] INFO:  - Processed attachments: 6
6:09:38 PM	Info	[2024-03-27T17:09:38.092Z] INFO:  - Executed actions: 7
6:09:38 PM	Info	[2024-03-27T17:09:38.094Z] INFO:  - Result status: ok
```
Why it's also getting other messages there?

**Comment by ahochsteger** [comment]
@DanielZanchi your config contains some errors:
The `query` should be part of the top-level `threads` section, have a look at the [config schema documentation](https://ahochsteger.github.io/gmail-processor/docs/reference/config-schema).
In addition you have to take care, if a thread contains multiple messages marking processed messages is not possible using labels, since labels are attached to the whole thread and not individual messages (a limitation of GMail).
Have a look at the [documentation of the `markProcessedMethod`](https://ahochsteger.github.io/gmail-processor/docs/reference/enum-types#markprocessedmethod) for more details.

I recommend to use the [Gmail Processor Playground](https://ahochsteger.github.io/gmail-processor/playground/) that performs a schema check and shows any syntax problems in the configuration.
Also have a look at the [new examples section in the documentation](https://ahochsteger.github.io/gmail-processor/docs/examples/).
