### ISSUE TITLE
Downloaded files/folders appendix added to google sheet rows

### ISSUE THREAD

**Issue by mrrosenthal85** [ahochsteger/gmail-processor#37]
Would be great to have a the feature where a new row is added to a google sheet google sheet populated by data from the created folders or files.  that way you can have a summary of what you are downloading and the details about all the files in one place.

**Comment by maxsnet** [comment]
@mrrosenthal85  I have done an update to the code so you can setup the path to a Google Spreadsheet Log File that contains 7 columns:
- Mail title
- Mail date
- Mail id
- Mail link
- File Origin ("Attachment" or "Thread")
- File Name
- File Link

**Comment by ahochsteger** [comment]
I'm closing this issue since [GMail2GDrive](https://github.com/ahochsteger/gmail-processor/tree/1.x) is discontinued and has been superseded by the much improved [Gmail Processor](https://github.com/ahochsteger/gmail-processor).
It provides a logSheet functionality that does what you expect. 
See the [Getting Started Guide](https://github.com/ahochsteger/gmail-processor/tree/main#getting-started) as well as the [Reference Docs](https://github.com/ahochsteger/gmail-processor/blob/main/docs/reference-docs.md#substitution-placeholder) for more information
