### ISSUE TITLE
Add parameter to skip marking a thread as processed

### ISSUE THREAD

**Issue by mmatviichuk** [ahochsteger/gmail-processor#43]
Would be great to have a feature to skip marking a thread as processed if the attachment was not matched to RegExp rule. Such parameter will be very helpful in case if you want to define different folders based on RegExp rule and use only one filter rule.

Potentially, it can increase Quota usage, but if you create rules carefully it will give you more flexibility in saving attachments.

**Comment by ahochsteger** [comment]
I'm closing this issue since [GMail2GDrive](https://github.com/ahochsteger/gmail-processor/tree/1.x) is discontinued and has been superseded by the much improved [Gmail Processor](https://github.com/ahochsteger/gmail-processor).
It provides a custom method way to mark threads or messages as processed.
See the [Getting Started Guide](https://github.com/ahochsteger/gmail-processor/tree/main#getting-started) as well as the [Reference Docs](https://github.com/ahochsteger/gmail-processor/blob/main/docs/reference-docs.md#substitution-placeholder) for more information.
