### ISSUE TITLE
Filter does not work properly (several emails with same subject)

### ISSUE THREAD

**Issue by tdunand** [ahochsteger/gmail-processor#44]
Scenario :
I receive in the same mailbox, everyday, sales reports for several locations (1 email per location)
Email subject is always the same
I created aliases to be able to filter the mails

Symptoms :
The filters are not considered properly, all messages with the same subject name are processed

Example :
I have in my inbox 3 emails with sales report :
 - 1 sent to ikentoo-location1@mycompany.tld
 - 1 sent to ikentoo-location2@mycompany.tld
 - 1 sent to ikentoo-location3@mycompany.tld
All 3 emails have the same subject "Your sales report"

I have for testing purpose only one rule for which the filter is
"filter": "to:ikentoo-location1@mycompany.tld"

But when I execute the program, the 3 emails are processed

I guess this could be because all emails have the same subject? 
I tried to apply different labels (before processing gmail2gdrive) but still the same issue.

Any idea how I could fix this?

Thanks
Thomas

**Comment by Elvic57** [comment]
It seems like I understood the issue here but don't know how to fix it(
In Gmail even if you turned of threaded view, all emails are still being treated by gmail to join them into threads. So when you start the script it checkes the first message in the thread. If that message had not been labelled yet the script process all the emails under that thread even if they were sent to different address like somth+1@email.com and somth+2@email.com. Even if they were already processed.
Can anyone suggest a fix for that?

**Comment by ahochsteger** [comment]
I think the main problem is, that the default Gmail Service always returns threads and not messages as a search result, thus also processing other mails that should not have been:
https://developers.google.com/apps-script/reference/gmail/gmail-app#search(String)

Fortunately there seems to be a way using the Advanced Gmail Service:
https://developers.google.com/apps-script/advanced/gmail

Here is some more information that may be of help:
https://stackoverflow.com/questions/53183973/google-apps-script-gmail-return-message-not-thread-via-filter

**Comment by ahochsteger** [comment]
I'm closing this issue since [GMail2GDrive](https://github.com/ahochsteger/gmail-processor/tree/1.x) is discontinued and has been superseded by the much improved [Gmail Processor](https://github.com/ahochsteger/gmail-processor).
It allows processing of multiple emails within the same thread which should solve your problem.
See the [Getting Started Guide](https://github.com/ahochsteger/gmail-processor/tree/main#getting-started) as well as the [Reference Docs](https://github.com/ahochsteger/gmail-processor/blob/main/docs/reference-docs.md#substitution-placeholder) for more information.
