### ISSUE TITLE
 Replacement of characters in the file name

### ISSUE THREAD

**Issue by Franz-65** [ahochsteger/gmail-processor#47]
Hello,
Thanks for the great script.
It works really well.
I would like to exchange letters for the filename that is saved.

I use this script for the filenames:
```
        "filter": "has:attachment from:service@XYZ.com",
        "folder": "XYZ/XYZ",
        "filenameFromRegexp": ".*\.pdf$"
```

However, the character "/" is often used in the filename of the attachment. e.g. "timeline/postbox3226.pdf"
How can I replace this with e.g. "-"
Does that work with the replace command? If so, how do I have to use this?

many thanks for your help

**Comment by ahochsteger** [comment]
I'm closing this issue since [GMail2GDrive](https://github.com/ahochsteger/gmail-processor/tree/1.x) is discontinued and has been superseded by the much improved [Gmail Processor](https://github.com/ahochsteger/gmail-processor).
It provides sophisticated RegEx matching and re-using the (named) matching groups for the final storage location.
See the [Getting Started Guide](https://github.com/ahochsteger/gmail-processor/tree/main#getting-started) as well as the [Reference Docs](https://github.com/ahochsteger/gmail-processor/blob/main/docs/reference-docs.md#substitution-placeholder) for more information.
