### ISSUE TITLE
Two files for different folders

### ISSUE THREAD

**Issue by jewishoffice** [ahochsteger/gmail-processor#52]
I receive several files in one email.
I want to move each file to another folder in Google Drive.

I tried so and it does not work:
   { // example"
        "filter": "has:attachment from:example@gmail.com‏",
        "folder": "'example1'",
        "filenameFromRegexp": "example1.*\.pdf$",
        "folder": "'example2'",
        "filenameFromRegexp": "example2.*\.pdf$"
      }, 

I would appreciate their help

**Comment by ahochsteger** [comment]
I'm closing this issue since [GMail2GDrive](https://github.com/ahochsteger/gmail-processor/tree/1.x) is discontinued and has been superseded by the much improved [Gmail Processor](https://github.com/ahochsteger/gmail-processor).
It provides the possibility to match different attachments of the same message and store them into different folders.
See the [Getting Started Guide](https://github.com/ahochsteger/gmail-processor/tree/main#getting-started) as well as the [Reference Docs](https://github.com/ahochsteger/gmail-processor/blob/main/docs/reference-docs.md#substitution-placeholder) for more information.
