### ISSUE TITLE
Getting error while saving the file to drive folder.

### ISSUE THREAD

**Issue by akashgurnani** [ahochsteger/gmail-processor#54]
Hi, I configured the script and it is finding and applying the labels perfectly but when it tried to save the file to drive folder it is throwing an error 

"Exception: Unexpected error while getting the method or property getRootFolder on object DriveApp."

I tried adding an existing folder or a new folder.

Nothing works. Please help.

**Comment by ahochsteger** [comment]
@akashgurnani do you still get that error?
If so, it would be helpful to post the logs and config here.
If not, it would be great to know how you could resolve it.

**Comment by ahochsteger** [comment]
Closing the issue due to inactivity.
Note, that [GMail2GDrive](https://github.com/ahochsteger/gmail-processor/tree/1.x) is discontinued and has been superseded by the much improved [Gmail Processor](https://github.com/ahochsteger/gmail-processor).
See the [Getting Started Guide](https://github.com/ahochsteger/gmail-processor/tree/main#getting-started) as well as the [Reference Docs](https://github.com/ahochsteger/gmail-processor/blob/main/docs/reference-docs.md) for more information.
