### ISSUE TITLE
[Feature] Merge thread PDF with attached PDF

### ISSUE THREAD

**Issue by jboggs326** [ahochsteger/gmail-processor#56]
Can we add functionality to add the message thread into an attached pdf file?  Would be willing to fund some development for that.

**Comment by ahochsteger** [comment]
@jboggs326, if I understand you correctly you want to take a PDF attached to an email of a thread and add more pages to the PDF that contains the entire emails of the complete thread - similar as you would print the whole thread, right?
Creating the PDF of the whole thread is already possible, I guess you are aware of that.

Merging two PDFs (the attached one + the generated thread PDF) is no easy task though since you'd need a PDF parser to do that (which is not part of the Google Apps Scripts Engine) and currently I'm only aware of hacky ways to do that which has a lot of problems with different PDF versions (see <https://stackoverflow.com/a/57533158/236784> for example).
An alternative solution would be to integrate a cloud service with an API that can merge two PDFs (see <https://stackoverflow.com/a/50842726/236784> for example). Depending on the cloud service and the volume of PDFs this may result in additional costs and complexity for the user of this script.

**Comment by ahochsteger** [comment]
Closing the issue due to inactivity.
Note, that [GMail2GDrive](https://github.com/ahochsteger/gmail-processor/tree/1.x) is discontinued and has been superseded by the much improved [Gmail Processor](https://github.com/ahochsteger/gmail-processor).
See the [Getting Started Guide](https://github.com/ahochsteger/gmail-processor/tree/main#getting-started) as well as the [Reference Docs](https://github.com/ahochsteger/gmail-processor/blob/main/docs/reference-docs.md) for more information.
