### ISSUE TITLE
Exclude files via regex

### ISSUE THREAD

**Issue by zzzZZZzzz9** [ahochsteger/gmail-processor#57]
I can not figure out how to add the regex ^(?!.*AGB).*$ to a rule in order to exclude all files containing "AGB" in the filename.
I tried `"filenameFromRegexp": "((?!.*AGB).*$)(.*\.pdf$|.*\.PDF$)"` but that did not work. Any ideas?

**Comment by moblo** [comment]
I would be interested in this as well. Has any solution been found? Thanks

**Comment by ahochsteger** [comment]
@zzzZZZzzz9, @moblo I'm closing this issue since [GMail2GDrive](https://github.com/ahochsteger/gmail-processor/tree/1.x) is discontinued and has been superseded by the much improved [Gmail Processor](https://github.com/ahochsteger/gmail-processor).
It provides the functionality you requested.
See the [Getting Started Guide](https://github.com/ahochsteger/gmail-processor/tree/main#getting-started) as well as the [Reference Docs](https://github.com/ahochsteger/gmail-processor/blob/main/docs/reference-docs.md#substitution-placeholder) for more information.
