### ISSUE TITLE
no rule to save in a folder that is the sender's email

### ISSUE THREAD

**Issue by rxng** [ahochsteger/gmail-processor#66]
not sure that this is an issue so sorry for posting in the wrong place, just wondering if there is a way to save in a folder that is the email address or name of the sender? can only see a few % replacements and sender email address isn't one of them

**Comment by soetheman** [comment]
Config.gs deployment allows you to define the related folder as part of the rule "filter": "from: .

**Comment by ahochsteger** [comment]
I'm closing this issue since [GMail2GDrive](https://github.com/ahochsteger/gmail-processor/tree/1.x) is discontinued and has been superseded by the much improved [Gmail Processor](https://github.com/ahochsteger/gmail-processor).
It provides the possibility to use the sender of the email using [substitution placeholders](https://github.com/ahochsteger/gmail-processor/blob/main/docs/reference-docs.md#substitution-placeholder) like `${message.from}`.
See the [Getting Started Guide](https://github.com/ahochsteger/gmail-processor/tree/main#getting-started) as well as the [Reference Docs](https://github.com/ahochsteger/gmail-processor/blob/main/docs/reference-docs.md#substitution-placeholder) for more information.
