### ISSUE TITLE
Function Not Working

### ISSUE THREAD

**Issue by r-vpk** [ahochsteger/gmail-processor#67]
H Experts,  I am new to Google Apps script and was trying out the script with customization based on the links provided in readme file. When I tried to test the function, it completed immediately, but did not work and Execution log is empty.

No Files Saved and label

9:19:05 AM	Notice	Execution started
9:19:05 AM	Notice	Execution completed

Am I doing something wrong ?

function getgmail2GDriveConfig() {
  return {
    // Global filter
    "globalFilter": "has:attachment -in:trash -in:drafts -in:spam",
    // gmail label for processed threads (will be created, if not existing):
    "processedLabel": "to-gdrive/processed",
    // Sleep time in milli seconds between processed messages:
    "sleepTime": 100,
    // Maximum script runtime in seconds (google scripts will be killed after 5 minutes):
    "maxRuntime": 280,
    // Only process message newer than (leave empty for no restriction; use d, m and y for day, month and year): 
    // example "newerThan": "2m"
    "newerThan": "2m",
    // Timezone for date/time operations:
    "timezone": "GMT",
    // Processing rules:
    "rules": [
      {
        // Bills - To save all PDF attachments in mails labelled Statusupdate to folder in googledrive - emailattach/Statusupdate
        "filter": "label:Statusupdate",
        "folder": "'emailattach/Statusupdate'",
        "filenameFromRegexp": ".*\.pdf$",
        "filenameTo": "yyyy-MM-dd-'%o-%d.txt'"
      },
    ]
  };
}

**Comment by ahochsteger** [comment]
I'm closing this issue since [GMail2GDrive](https://github.com/ahochsteger/gmail-processor/tree/1.x) is discontinued and has been superseded by the much improved [Gmail Processor](https://github.com/ahochsteger/gmail-processor).
See the [Getting Started Guide](https://github.com/ahochsteger/gmail-processor/tree/main#getting-started) as well as the [Reference Docs](https://github.com/ahochsteger/gmail-processor/blob/main/docs/reference-docs.md#substitution-placeholder) for more information.
