### ISSUE TITLE
Weird issue when using get.from or a header parser to get the name of an email sender.

### ISSUE THREAD

**Issue by wondersalmon** [ahochsteger/gmail-processor#68]
Hello! First of all, I want to thank the author of the script for his work - this is a very useful and necessary project, for example, it helps me automate the collection and sorting of students' homework.

**Now the problem:** I need to convert downloaded attachment names to sender names (ideally First and last name, no email address). When processing names with Cyrillic characters through getting from, there are no problems - the files are saved under the desired name, however, if the name and surname of the sender are written in Latin, I get the error "**Exception: Invalid argument: John Doe**". I've tried getting names through getting from and through the header parser.
Parser:
```
function parseEmailHeader(message) {
  var header = message.getFrom().trim();

  var extract = { name: '', email: '' };

  var emails = header.match(/[^@<\s]+@[^@\s>]+/g);

  if (emails) {
    extract.email = emails[0];
  }

  var names = header.split(/\s+/);

  if (names.length > 1) {
    names.pop();
    extract.name = names.join(' ').replace(/"/g, '');
  }

  return extract;
```

And the function call:

```
var sender = parseEmailHeader(message);
      var new_filename = rule.filenameTo.replace('%s',message.getSubject()).replace("%d", String(rule_counter++)).replace('%o', original_attachment_name).replace('%f', sender.name.replace(" ", "_"))
```
If there is a better solution, I'd be happy to know. Now, unfortunately, it was not possible to achieve the correct processing of names.

**Comment by ahochsteger** [comment]
@wondersalmon thanks for your kind words! :-)
I'm closing this issue since [GMail2GDrive](https://github.com/ahochsteger/gmail-processor/tree/1.x) is discontinued and has been superseded by the much improved [Gmail Processor](https://github.com/ahochsteger/gmail-processor).
It provides a sophisticated possibility to extract values using named RegEx groups which may be help to achieve what you want.
See the [Getting Started Guide](https://github.com/ahochsteger/gmail-processor/tree/main#getting-started) as well as the [Reference Docs](https://github.com/ahochsteger/gmail-processor/blob/main/docs/reference-docs.md#substitution-placeholder) for more information.
