### ISSUE TITLE
not an issue more of a request! add a column to csv file with date and or filename.

### ISSUE THREAD

**Issue by GNewbs** [ahochsteger/gmail-processor#70]
Hi 

I am experimenting with gmail to gdrive to do a bit of automation. very new to scripts so please be nice!! 

I have got gmail to drive working for the attachments I have running. thank you very useful! 

I would like to add a column(s) of data to particular csv files that the script processes... so for example when the script finds a csv file that meet the criteria it creates a two new column in the csv which contain the file name and the date the script processed the file and moved it to google drive. Is that possible? 

many thanks in advance! 

G

**Comment by ahochsteger** [comment]
@GNewbs I'm closing this issue since [GMail2GDrive](https://github.com/ahochsteger/gmail-processor/tree/1.x) is discontinued and has been superseded with the much improved [Gmail Processor](https://github.com/ahochsteger/gmail-processor).
It provides a logSheet functionality to write different columns like filename, date (and many others) into a Google Spreadsheet. It may not be exactly what you were looking for but may be of interest nevertheless. 
See the [Getting Started Guide](https://github.com/ahochsteger/gmail-processor/tree/main#getting-started) as well as the [Reference Docs](https://github.com/ahochsteger/gmail-processor/blob/main/docs/reference-docs.md#substitution-placeholder) for more information.
