### ISSUE TITLE
Request-Ability to Exclude Attachments by Extension

### ISSUE THREAD

**Issue by czdz** [ahochsteger/gmail-processor#71]
It would be very helpful if I could exclude attachments from downloading based on the file extension. Is this currently possible? If not, then I am kindly requesting this feature.

Great script even without this functionality. Many thanks!

**Comment by ahochsteger** [comment]
@czdz I'm closing this issue since [GMail2GDrive](https://github.com/ahochsteger/gmail-processor/tree/1.x) has been superseded with the much improved [Gmail Processor](https://github.com/ahochsteger/gmail-processor) which provide advanced matching possibilities among many other improvements.
See the [Getting Started Guide](https://github.com/ahochsteger/gmail-processor/tree/main#getting-started) as well as the [Reference Docs](https://github.com/ahochsteger/gmail-processor/blob/main/docs/reference-docs.md#substitution-placeholder) for more information.
