### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by soetheman** [ahochsteger/gmail-processor#77]
Error "TypeError: Cannot read properties of undefined (reading 'replace')" is occuring (processing line 178).
This error is reproducable as it shows up using the current master code. I left the config.gs untouched, except the 2nd processing rule, in order to match my test gmail message w/ attachment.
The attachment is saved to Gdrive, however due to this error the rest of function processMessage isn't performed.
Thanks for commenting this behavior.
Regards, paul,

INFO: Starting mail attachment processing.
INFO:   Processing rule: has:attachment -in:trash -in:drafts -in:spam to:my.name+scans@gmail.com -label:to-gdrive/processed newer_than:2m
INFO:   Processing rule: has:attachment -in:trash -in:drafts -in:spam from:soetemanpaul@gmail.com -label:to-gdrive/processed newer_than:2m
INFO:     Processing thread: fghggh (runtime: 0.204s/280s)
INFO:       Processing message: fghggh (185a2c754e4eb3af)
INFO:         Processing attachment: adv04.png
Saving to folderExamples/soetemanPaul
TypeError: Cannot read properties of undefined (reading 'replace')
INFO:   Processing rule: has:attachment -in:trash -in:drafts -in:spam to:my.name+scans@gmail.com -label:to-gdrive/processed newer_than:2m
[Naamloos document.pdf](https://github.com/ahochsteger/gmail2gdrive/files/10396292/Naamloos.document.pdf)

**Comment by ardigan6** [comment]
Try #76

**Comment by ahochsteger** [comment]
Closing the issue due to inactivity.
Note, that [GMail2GDrive](https://github.com/ahochsteger/gmail-processor/tree/1.x) is discontinued and has been superseded with the much improved [Gmail Processor](https://github.com/ahochsteger/gmail-processor).
See the [Getting Started Guide](https://github.com/ahochsteger/gmail-processor/tree/main#getting-started) as well as the [Reference Docs](https://github.com/ahochsteger/gmail-processor/blob/main/docs/reference-docs.md) for more information.
