### ISSUE TITLE
Nothing happening

### ISSUE THREAD

**Issue by Porfavorio** [ahochsteger/gmail-processor#78]
I setup the script as instructed and adjusted the config in regard of 

```
folder "Myfolder"
        "filter": "to:mymail@mytld.net",
        "folder": "'Myfolder'"
      },
```
I set the time frame to newer than 5d and sent an email with attachment to mymail@mytld.net which does automatically get the label setup. But the documents is not placed in MyFolder.
There is no error in executing but nothing is happening.

Any ideas?

**Comment by ahochsteger** [comment]
To help with your problem it would be helpful if you could provide the exact config snipped (yours contains syntax errors) as well as the log output of the script.

**Comment by ahochsteger** [comment]
Closing the issue due to inactivity.
Note, that [GMail2GDrive](https://github.com/ahochsteger/gmail-processor/tree/1.x) is discontinued and has been superseded with the much improved [Gmail Processor](https://github.com/ahochsteger/gmail-processor).
See the [Getting Started Guide](https://github.com/ahochsteger/gmail-processor/tree/main#getting-started) as well as the [Reference Docs](https://github.com/ahochsteger/gmail-processor/blob/main/docs/reference-docs.md) for more information.
